pub mod align_of;
mod builtin;
mod checker;
mod collector;
mod errors;
mod formatter;
pub mod interpreter;
mod literals;
mod monomorphizations;
pub mod size_of;
mod table;
mod ty_lower;
mod unify;
pub mod validator;
mod vars;

pub use boron_types::infer_ty::{InferTy, TyVar, TyVarKind, TypeScheme};
pub use builtin::*;
pub use checker::{typeck_hir, TyChecker};
pub use literals::*;
pub use table::{InferCtx, TypeEnv, TypeTable};
